const { queryDatabase } = require('../lib_login/db');
const PythonRunner = require('../lib_execution/PythonRunner');
const axios = require('axios'); // Assuming axios is available or use fetch

class GenerationService {
    constructor() {
        this.runner = new PythonRunner();
        // In real app, load from process.env.OPENAI_API_KEY
    }

    /**
     * Triggers the generation of a new problem for a specific CT Node.
     * @param {string} ctNodeId - The concept to focus on (e.g., 'Loop')
     * @param {string} difficulty - 'EASY', 'MEDIUM', 'HARD'
     */
    async generateProblem(ctNodeId, difficulty) {
        console.log(`🎨 Creator Engine: Generating ${difficulty} problem for Node ${ctNodeId}...`);

        try {
            // 1. Fetch Node Details
            const node = await queryDatabase('SELECT name, description FROM CT_Nodes WHERE id = ?', [ctNodeId]);
            if (node.length === 0) return null;
            const concept = node[0].name;

            // 2. Call LLM (Mocking the call for now)
            // In production: await this.callLLM(concept, difficulty);
            const generated = await this.mockLLM(concept, difficulty);

            console.log('🤖 LLM Generated:', generated.title);

            // 3. Verify Code (Self-Correction)
            const isValid = await this.verifyProblem(generated);

            if (isValid) {
                // 4. Save to DB
                await this.saveProblem(generated, ctNodeId);
                return generated;
            } else {
                console.warn('⚠️ Generation failed verification. Retrying...');
                // Implement retry logic here
                return null;
            }

        } catch (error) {
            console.error('❌ Generation Error:', error);
            return null;
        }
    }

    async mockLLM(concept, difficulty) {
        // Simulating LLM response
        return {
            title: `${concept} Practice: The Auto-Generator`,
            description: `Write a Python function that demonstrates ${concept}. This problem was automatically generated by the Creator Engine.`,
            difficulty: difficulty,
            code_template: `def solution():\n    # Write your code here\n    pass`,
            solution_code: `def solution():\n    return "Hello ${concept}"`,
            test_cases: [
                { input: "", output: `Hello ${concept}`, is_hidden: false }
            ]
        };
    }

    /**
     * Verifies the generated problem by running the solution against test cases.
     */
    async verifyProblem(problem) {
        console.log('🔍 Verifying generated solution...');
        try {
            // Run the "solution_code" against "test_cases"
            const results = await this.runner.runTestCases(problem.solution_code, problem.test_cases);

            // Check if all passed
            const allPassed = results.every(r => r.status === 'PASS');

            if (allPassed) {
                console.log('✅ verification PASSED.');
                return true;
            } else {
                console.error('❌ verification FAILED:', results);
                return false;
            }
        } catch (e) {
            console.error('Verification Exception:', e);
            return false;
        }
    }

    async saveProblem(problem, ctNodeId) {
        const result = await queryDatabase(`
            INSERT INTO Problems 
            (title, description, difficulty, category, created_by, is_active)
            VALUES (?, ?, ?, 'GENERATED', 'TheCreator', 1)
        `, [problem.title, problem.description, problem.difficulty]);

        const problemId = result.insertId;

        // Save Test Cases (simplified)
        // In real app, insert into TestCases table

        // Link to CT Node
        await queryDatabase(`
            INSERT INTO Problem_Map (problem_id, ct_node_id, contribution_weight)
            VALUES (?, ?, 100)
        `, [problemId, ctNodeId]);

        console.log(`💾 Saved Problem ${problemId} to Database.`);
    }
}

module.exports = GenerationService;
