-- ================================================================================
-- Fix Content Map Data (Migrate to ContentMap)
-- ================================================================================

-- Drop the temporary table created by mistake
DROP TABLE IF EXISTS content_map;

-- Make sure ContentMap exists (schema from before)
-- Note: We assume the table already exists as per the user's DESCRIBE output.
-- We will NOT create it here to avoid conflicts, but we will TRUNCATE it.

-- Clear existing data in ContentMap to avoid duplicates
TRUNCATE TABLE ContentMap;

INSERT INTO ContentMap (platform, category, content_name, content_type, difficulty_level, is_active) VALUES
('scratch', 'CPS', '1-1. 동네 산책 길잡이', 'basic', 1, 1),
('scratch', 'CPS', '1-2. 미래의 애니메이터', 'basic', 1, 1),
('scratch', 'CPS', '1-3. 내 소중한 보물을 숨겨 줘', 'basic', 1, 1),
('scratch', 'CPS', '1-4. 백발 발레리나의 마지막 무대', 'basic', 1, 1),
('scratch', 'CPS', '2-1. 무사히 착륙하라!', 'basic', 2, 1),
('scratch', 'CPS', '2-2. 불꽃이 팡! 팡! 팡!', 'basic', 2, 1),
('scratch', 'CPS', '2-3. 엄마! TV 봐도 돼요', 'basic', 2, 1),
('scratch', 'CPS', '2-4. 어째 으스스한 기분이 들어', 'basic', 2, 1),
('scratch', 'CPS', '3-1. 화산 폭발 일보 직전!', 'basic', 3, 1),
('scratch', 'CPS', '3-2. 색이 변하는 나뭇잎', 'basic', 3, 1),
('scratch', 'CPS', '3-3. 꼬마 해녀의 삶', 'basic', 3, 1),
('scratch', 'CPS', '3-4. 음악에 몸을 맡겨 봐', 'basic', 3, 1),
('scratch', 'CPS', '4-1. 피아노 연주(feat. 흥얼흥얼)', 'basic', 4, 1),
('scratch', 'CPS', '4-2. 내 기분이 궁금해', 'basic', 4, 1),
('scratch', 'CPS', '4-3. 어! 어! 어! 어!', 'basic', 4, 1),
('scratch', 'CPS', '4-4. 퀴즈 쇼! 정답을 맞혀라', 'basic', 4, 1),
('scratch', 'CPS', '5-1. 꽤 멋진 별명', 'basic', 5, 1),
('scratch', 'CPS', '5-2. 삐-빅! 날씨 정보 입력 완료!', 'basic', 5, 1),
('scratch', 'CPS', '5-3. 목표는 세계 일주', 'basic', 5, 1),
('scratch', 'CPS', '5-4. 클릭만 하면 돼', 'basic', 5, 1),
('scratch', 'CPS', '6-1. 여기는 식물 연구소입니다', 'basic', 6, 1),
('scratch', 'CPS', '6-2. 알뜰살뜰 경제 대장', 'basic', 6, 1),
('scratch', 'CPS', '6-3. 째깍째깍 돌아라', 'basic', 6, 1),
('entry', 'CPE', 'CPE 1-1. 토끼와 거북이의 재대결', 'basic', 1, 1),
('entry', 'CPE', 'CPE 1-2. 은혜갚은 개미', 'basic', 1, 1),
('entry', 'CPE', 'CPE 1-3. 비겁한 박쥐', 'basic', 1, 1),
('entry', 'CPE', 'CPE 1-4. 까마귀와 물병', 'basic', 1, 1),
('entry', 'CPE', 'CPE 2-1. 사자와 생쥐', 'basic', 2, 1),
('entry', 'CPE', 'CPE 2-2. 현대판 양치기 소년과 늑대', 'basic', 2, 1),
('entry', 'CPE', 'CPE 2-3. 개구리의 최후', 'basic', 2, 1),
('entry', 'CPE', 'CPE 2-4. 고양이 목에 방울 달기', 'basic', 2, 1),
('entry', 'CPE', 'CPE 3-1. 만 나이 계산기', 'basic', 3, 1),
('entry', 'CPE', 'CPE 3-2. 평면도형과 각도', 'basic', 3, 1),
('entry', 'CPE', 'CPE 3-3. 간접흡연은 싫어요', 'basic', 3, 1),
('entry', 'CPE', 'CPE 3-4. 도형의 배열에서 규칙 찾기', 'basic', 3, 1),
('entry', 'CPE', 'CPE 4-1. 내 손으로 만드는 라인트레이서', 'basic', 4, 1),
('entry', 'CPE', 'CPE 4-2. 발표자 추첨 프로그램', 'basic', 4, 1),
('entry', 'CPE', 'CPE 4-3. 레트로 게임 만들기(1)', 'basic', 4, 1),
('entry', 'CPE', 'CPE 4-4. 레트로 게임 만들기(2)', 'basic', 4, 1),
('entry', 'CPE', 'CPE 5-1. 거북목 탈출 게임', 'basic', 5, 1),
('entry', 'CPE', 'CPE 5-2. 국어퀴즈', 'basic', 5, 1),
('entry', 'CPE', 'CPE 5-3. 소방구역지킴이(스크래치)', 'basic', 5, 1),
('entry', 'CPE', 'CPE 5-4. 호러 메이즈', 'basic', 5, 1),
('entry', 'CPE', 'CPE 6-1. 힐링체험! 돌을키워라!', 'basic', 6, 1),
('entry', 'CPE', 'CPE 6-2. 캐치보이스피싱', 'basic', 6, 1),
('entry', 'CPE', 'CPE 6-3. 키오스크 어렵지않아요', 'basic', 6, 1),
('entry', 'CPE', 'CPE 6-4. 스마트 AI 냉장고', 'basic', 6, 1),
('entry', 'CPA', 'CPA 1-1. 음성으로 드론을 조정한다고?', 'basic', 1, 1),
('entry', 'CPA', 'CPA 1-2. 나를 대신해서 책을 읽어주는 오디오북', 'basic', 1, 1),
('entry', 'CPA', 'CPA 1-3.번역을 도와줘!', 'basic', 1, 1),
('entry', 'CPA', 'CPA 1-4. 인공지능 코디 스타일봇', 'basic', 1, 1),
('entry', 'CPA', 'CPA 2-1. 나 혼자 게임한다(AI와 가위바위보)', 'basic', 2, 1),
('entry', 'CPA', 'CPA 2-2. 나만의 인공지능DJ', 'basic', 2, 1),
('entry', 'CPA', 'CPA 2-3. 꿈꿔왔던 나의 집, 스마트홈', 'basic', 2, 1),
('entry', 'CPA', 'CPA 2-4. 졸음운전은 안돼요!', 'basic', 2, 1),
('entry', 'CPA', 'CPA 3-1. 요리 재료 양 예측하기', 'basic', 3, 1),
('entry', 'CPA', 'CPA 3-2. 음료 급식을 추천해줘', 'basic', 3, 1),
('entry', 'CPA', 'CPA 3-3. 해커톤 대회 장소 정하기', 'basic', 3, 1),
('entry', 'CPA', 'CPA 3-4. 꽃의 품종을 구분하는 인공지능 앱', 'basic', 3, 1),
('appinventor', 'CTR앱인벤터', '1-1. 동물카드어플만들기: 변수', 'basic', 1, 1),
('appinventor', 'CTR앱인벤터', '1-2. 동물카드어플만들기: 리스트', 'basic', 1, 1),
('appinventor', 'CTR앱인벤터', '1-3. 동물카드어플만들기: 함수', 'basic', 1, 1),
('appinventor', 'CTR앱인벤터', '1-4. 동물카드어플만들기: 레이아웃', 'basic', 1, 1),
('appinventor', 'CTR앱인벤터', '2-1. 플라잉버드: 캔버스/ 이미지스프라이트,', 'basic', 2, 1),
('appinventor', 'CTR앱인벤터', '2-2. 플라잉버드: 리스트, 반복', 'basic', 2, 1),
('appinventor', 'CTR앱인벤터', '2-3. 플라잉버드: 조건문, 변수', 'basic', 2, 1),
('appinventor', 'CTR앱인벤터', '2-4. 플라잉버드: 함수', 'basic', 2, 1),
('appinventor', 'CTR앱인벤터', '3-1. 주정차단속어플: 카메라/ 목록, 변수', 'basic', 3, 1),
('appinventor', 'CTR앱인벤터', '3-2. 주정차단속어플: 조건문, 반복', 'basic', 3, 1),
('appinventor', 'CTR앱인벤터', '3-3. 주정차단속어플: 함수', 'basic', 3, 1),
('appinventor', 'CTR앱인벤터', '3-4. 주정차단속어플: 레이아웃', 'basic', 3, 1),
('appinventor', 'CTR앱인벤터', '4-1. 챗봇어플: 구글AI/ 리스트, 변수', 'basic', 4, 1),
('appinventor', 'CTR앱인벤터', '4-2. 챗봇어플: 조건문, 반복', 'basic', 4, 1),
('appinventor', 'CTR앱인벤터', '4-3. 챗봇어플: 함수', 'basic', 4, 1),
('appinventor', 'CTR앱인벤터', '4-4. 챗봇어플: 레이아웃', 'basic', 4, 1),
('appinventor', 'CTR앱인벤터', '5-1. 틱택톡: 캔버스, 이미지스프라이트, 변수', 'basic', 5, 1),
('appinventor', 'CTR앱인벤터', '5-2. 틱택톡: 리스트, 반복', 'basic', 5, 1),
('appinventor', 'CTR앱인벤터', '5-3. 틱택톡: 조건문', 'basic', 5, 1),
('appinventor', 'CTR앱인벤터', '5-4. 틱택톡: 함수', 'basic', 5, 1),
('appinventor', 'CTR앱인벤터', '6-1. 날씨어플: API, 변수', 'basic', 6, 1),
('appinventor', 'CTR앱인벤터', '6-2. 날씨어플: 리스트, 반복', 'basic', 6, 1),
('appinventor', 'CTR앱인벤터', '6-3. 날씨어플: 조건문', 'basic', 6, 1),
('appinventor', 'CTR앱인벤터', '6-4. 날씨어플: 함수', 'basic', 6, 1),
('python', 'CTR 파이썬 1호', '1. 변수, 입출력', 'basic', 1, 1),
('python', 'CTR 파이썬 1호', '2. 기본자료형', 'basic', 1, 1),
('python', 'CTR 파이썬 1호', '3. list, tuple', 'basic', 1, 1),
('python', 'CTR 파이썬 1호', '4. dic, set, bool', 'basic', 1, 1),
('python', 'CTR 파이썬 1호', '5. 마무리테스트 (CTR 파이썬 1호)', 'basic', 1, 1),
('python', 'CTR 파이썬 2호', '1. 조건문(if, else, elif)', 'basic', 2, 1),
('python', 'CTR 파이썬 2호', '2. 반복문(while, for)', 'basic', 2, 1),
('python', 'CTR 파이썬 2호', '3. 함수(function)', 'basic', 2, 1),
('python', 'CTR 파이썬 2호', '4. 파일 읽고 쓰기', 'basic', 2, 1),
('python', 'CTR 파이썬 2호', '5. 마무리테스트 (CTR 파이썬 2호)', 'basic', 2, 1),
('python', 'CTR 파이썬 3호', '1. 클래스(class)', 'basic', 3, 1),
('python', 'CTR 파이썬 3호', '2. 모듈(module)', 'basic', 3, 1),
('python', 'CTR 파이썬 3호', '3. 예외처리(exception)', 'basic', 3, 1),
('python', 'CTR 파이썬 3호', '4. 라이브러리', 'basic', 3, 1),
('python', 'CTR 파이썬 3호', '5. 마무리테스트 (CTR 파이썬 3호)', 'basic', 3, 1),
('python', 'CTR 파이썬 프로젝트', '1. 포켓몬배틀', 'basic', 4, 1),
('python', 'CTR 파이썬 프로젝트', '2. 단어맞추기: 행맨', 'basic', 4, 1),
('python', 'CTR 파이썬 프로젝트', '3. 햄버거 키오스크', 'basic', 4, 1),
('python', 'CTR 파이썬 프로젝트', '4. 음원차트 크롤링', 'basic', 4, 1),
('dataanalysis', '1장: 데이터분석 개요', '1. 데이터 분석 개요', 'basic', 1, 1),
('dataanalysis', '2장: 데이터시각화', '2-1. 데이터 구조와 특성', 'basic', 2, 1),
('dataanalysis', '2장: 데이터시각화', '2-2. 데이터시각화기법', 'basic', 2, 1),
('dataanalysis', '2장: 데이터시각화', '2-3. 기술통계와 데이터요약', 'basic', 2, 1),
('dataanalysis', '2장: 데이터시각화', '2-4. AI도구를 활용한 EDA와 전통적방식 비교', 'basic', 2, 1),
('dataanalysis', '2장: 데이터시각화', '2-5. 실제 데이터셋 탐색', 'basic', 2, 1),
('dataanalysis', '2장: 데이터시각화', '2-6. 완료', 'basic', 2, 1),
('dataanalysis', '3장: 확률과통계', '3-1. 확률분포와 통계적 개념', 'basic', 3, 1),
('dataanalysis', '3장: 확률과통계', '3-2. 가설 검정의 이해', 'basic', 3, 1),
('dataanalysis', '3장: 확률과통계', '3-3. 상관관계와 인과관계', 'basic', 3, 1),
('dataanalysis', '3장: 확률과통계', '3-4. AI가 생성한 통계 분석 결과 검증', 'basic', 3, 1),
('dataanalysis', '3장: 확률과통계', '3-5. 통계적 가설 검정수행', 'basic', 3, 1),
('dataanalysis', '4장: 데이터전처리', '4-1. 결측치와 이상치 처리', 'basic', 4, 1),
('dataanalysis', '4장: 데이터전처리', '4-2. 데이터변환과 정규화', 'basic', 4, 1),
('dataanalysis', '4장: 데이터전처리', '4-3. 특성(feature)공학', 'basic', 4, 1),
('dataanalysis', '4장: 데이터전처리', '4-4. AI도구를 활용한 자동 전처리와 한계점', 'basic', 4, 1),
('dataanalysis', '4장: 데이터전처리', '4-5. 실제 데이터 전처리 파이프라인 구축', 'basic', 4, 1),
('dataanalysis', '5장: 머신러닝', '5-1. 지도학습과 비지도학습', 'basic', 5, 1),
('dataanalysis', '5장: 머신러닝', '5-2. 분류 알고리즘의 이해와 구현', 'basic', 5, 1),
('dataanalysis', '5장: 머신러닝', '5-3. 회귀 알고리즘의 이해와 구현', 'basic', 5, 1),
('dataanalysis', '5장: 머신러닝', '5-4. 모델 평가와 검증 방법', 'basic', 5, 1),
('dataanalysis', '5장: 머신러닝', '5-5. 예측모델 개발 및 평가', 'basic', 5, 1),
('dataanalysis', '6장: 앙상블기법', '6-1. 앙상블 학습과 투표 방식', 'basic', 6, 1),
('dataanalysis', '6장: 앙상블기법', '6-2. 차원 축소와 군집화', 'basic', 6, 1),
('dataanalysis', '6장: 앙상블기법', '6-3. 하이퍼파라미터 최적화', 'basic', 6, 1),
('dataanalysis', '6장: 앙상블기법', '6-4. AI와 협업을 통한 모델 개선', 'basic', 6, 1),
('dataanalysis', '6장: 앙상블기법', '6-5. 복합모델 구축 및 최적화', 'basic', 6, 1),
('dataanalysis', '7장: 프롬프트엔지니어링', '7-1. 프롬프트엔지니어링 기법', 'basic', 7, 1),
('dataanalysis', '7장: 프롬프트엔지니어링', '7-2. AI 생성코드 검증 및 최적화', 'basic', 7, 1),
('dataanalysis', '7장: 프롬프트엔지니어링', '7-3. 자동화와수동 작업의 균형찾기', 'basic', 7, 1),
('dataanalysis', '7장: 프롬프트엔지니어링', '7-4. 대규모 언어모델을 활용한 데이터분석', 'basic', 7, 1),
('dataanalysis', '7장: 프롬프트엔지니어링', '7-5. AI보조분석 워크플로우 구축', 'basic', 7, 1),
('dataanalysis', '8장: 시계열데이터처리', '8-1. 시계열 데이터의 특성과 전처리', 'basic', 8, 1),
('dataanalysis', '8장: 시계열데이터처리', '8-2. 전통적 시계열모델(ARIMA, 지수평활법)', 'basic', 8, 1),
('dataanalysis', '8장: 시계열데이터처리', '8-3. 머신러닝기반 시계열 예측', 'basic', 8, 1),
('dataanalysis', '8장: 시계열데이터처리', '8-4. 딥러닝을 활용한 시계열 예측', 'basic', 8, 1),
('dataanalysis', '8장: 시계열데이터처리', '8-5. 실제 시계열 데이터 예측 및 비교분석', 'basic', 8, 1);